'''
Authors: Jared Galloway, Jeff Adrion
Modified by J.Min
'''

from ReLERNN.imports import *

class SequenceBatchGenerator:

    '''
    This class, SequenceBatchGenerator, provides batches of genotype matrices
    from a given .trees directory (generated by the Simulator class) prepped
    according to the given parameters.

    Use ``to_dataset()`` to obtain a ``tf.data.Dataset`` pipeline with
    asynchronous prefetching for efficient GPU training.

    Use TFRecord when available for faster data loading

    ``__getitem__`` and ``__len__`` are retained for backward compatibility
    (used by ReLERNN_BSCORRECT via batchGenerator.__getitem__(0)).

    def __getitem__(self, idx):

    def __data_generation(self, batchTreeIndices):

    '''

    #Initialize the member variables which largely determine the data prepping heuristics
    #in addition to the .trees directory containing the data from which to generate the batches
    def __init__(self,
            treesDirectory,
            targetNormalization = 'zscore',
            batchSize=64,
            maxLen=None,
            frameWidth=0,
            center=False,
            sortInds=False,
            ancVal = -1,
            padVal = -1,
            derVal = 1,
            realLinePos = True,
            posPadVal = 0,
            shuffleExamples = True,
            splitFLAG = False,
            seqD = None,
            maf = None,
            hotspots = False,
            seed = None,
            useTFRecord = True, 
            **kwargs
            ):

        self.treesDirectory = treesDirectory
        self.targetNormalization = targetNormalization
        infoFilename = os.path.join(self.treesDirectory,"info.p")
        self.infoDir = pickle.load(open(infoFilename,"rb"))
        self.batch_size = batchSize
        self.maxLen = maxLen
        self.frameWidth = frameWidth
        self.center = center
        self.sortInds=sortInds
        self.ancVal = ancVal
        self.padVal = padVal
        self.derVal = derVal
        self.realLinePos = realLinePos
        self.posPadVal = posPadVal
        self.indices = np.arange(self.infoDir["numReps"])
        self.shuffleExamples = shuffleExamples
        self.splitFLAG = splitFLAG
        self.seqD = seqD
        self.maf = maf
        self.hotspots = hotspots
        self.seed = seed
        self.useTFRecord = useTFRecord

        if self.seed:
            os.environ['PYTHONHASHSEED']=str(self.seed)
            random.seed(self.seed)
            np.random.seed(self.seed)

        if(targetNormalization != None):
            if self.hotspots:
                self.normalizedTargets = self.normalizeTargetsBinaryClass()
            else:
                self.normalizedTargets = self.normalizeTargets()

        if(shuffleExamples):
            np.random.shuffle(self.indices)

    def sort_min_diff(self,amat):
        '''this function takes in a SNP matrix with indv on rows and returns the same matrix with indvs sorted by genetic similarity.
        this problem is NP, so here we use a nearest neighbors approx.  it's not perfect, but it's fast and generally performs ok.
        assumes your input matrix is a numpy array'''

        mb = NearestNeighbors(n_neighbors=len(amat), metric='manhattan').fit(amat)
        v = mb.kneighbors(amat)
        smallest = np.argmin(v[0].sum(axis=1))
        return amat[v[1][smallest]]

    def pad_HapsPos(self,haplotypes,positions,maxSNPs=None,frameWidth=0,center=False):
        '''
        pads the haplotype and positions tensors
        to be uniform with the largest tensor
        '''

        haps = haplotypes
        pos = positions

        #Normalize the shape of all haplotype vectors with padding
        for i in range(len(haps)):
            numSNPs = haps[i].shape[0]
            paddingLen = maxSNPs - numSNPs
            if(center):
                prior = paddingLen // 2
                post = paddingLen - prior
                haps[i] = np.pad(haps[i],((prior,post),(0,0)),"constant",constant_values=2.0)
                pos[i] = np.pad(pos[i],(prior,post),"constant",constant_values=-1.0)

            else:
                if(paddingLen < 0):
                    haps[i] = np.pad(haps[i],((0,0),(0,0)),"constant",constant_values=2.0)[:paddingLen]
                    pos[i] = np.pad(pos[i],(0,0),"constant",constant_values=-1.0)[:paddingLen]
                else:
                    haps[i] = np.pad(haps[i],((0,paddingLen),(0,0)),"constant",constant_values=2.0)
                    pos[i] = np.pad(pos[i],(0,paddingLen),"constant",constant_values=-1.0)

        haps = np.array(haps,dtype='float32')
        pos = np.array(pos,dtype='float32')

        if(frameWidth):
            fw = frameWidth
            haps = np.pad(haps,((0,0),(fw,fw),(fw,fw)),"constant",constant_values=2.0)
            pos = np.pad(pos,((0,0),(fw,fw)),"constant",constant_values=-1.0)

        return haps,pos

    def padAlleleFqs(self,haplotypes,positions,maxSNPs=None,frameWidth=0,center=False):
        '''
        convert haps to allele frequencies, normalize, and
        pad the haplotype and positions tensors
        to be uniform with the largest tensor
        '''

        haps = haplotypes
        positions = positions
        fqs, pos = [], []

        # Resample to sequencing depth and convert to allele frequencies
        for i in range(len(haps)):
            tmp_freqs = []
            tmp_pos = []
            fqs_list = haps[i].tolist()
            for j in range(len(fqs_list)):

                if self.seqD != -9:
                    ## Resample
                    z = resample(fqs_list[j], n_samples=self.seqD, replace=True)
                    raw_freq = round(np.count_nonzero(z)/float(len(z)),3)
                    if self.maf <= raw_freq < 1.0:
                        tmp_freqs.append(raw_freq)
                        tmp_pos.append(positions[i][j])
                else:
                    ## Don't resample
                    raw_freq = round(np.count_nonzero(fqs_list[j])/float(len(fqs_list[j])),3)
                    tmp_freqs.append(raw_freq)
                    tmp_pos.append(positions[i][j])

            fqs.append(np.array(tmp_freqs))
            pos.append(np.array(tmp_pos))

        # Normalize
        fqs = self.normalizeAlleleFqs(fqs)

        # Pad
        for i in range(len(fqs)):
            numSNPs = fqs[i].shape[0]
            paddingLen = maxSNPs - numSNPs
            if(center):
                prior = paddingLen // 2
                post = paddingLen - prior
                fqs[i] = np.pad(fqs[i],(prior,post),"constant",constant_values=-1.0)
                pos[i] = np.pad(pos[i],(prior,post),"constant",constant_values=-1.0)

            else:
                if(paddingLen < 0):
                    fqs[i] = np.pad(fqs[i],(0,0),"constant",constant_values=-1.0)[:paddingLen]
                    pos[i] = np.pad(pos[i],(0,0),"constant",constant_values=-1.0)[:paddingLen]
                else:
                    fqs[i] = np.pad(fqs[i],(0,paddingLen),"constant",constant_values=-1.0)
                    pos[i] = np.pad(pos[i],(0,paddingLen),"constant",constant_values=-1.0)

        fqs = np.array(fqs,dtype='float32')
        pos = np.array(pos,dtype='float32')

        if(frameWidth):
            fw = frameWidth
            fqs = np.pad(fqs,((0,0),(fw,fw)),"constant",constant_values=-1.0)
            pos = np.pad(pos,((0,0),(fw,fw)),"constant",constant_values=-1.0)

        return fqs,pos

    def normalizeTargets(self):

        '''
        We want to normalize all targets.
        '''

        norm = self.targetNormalization
        nTargets = copy.deepcopy(self.infoDir['rho'])

        if(norm == 'zscore'):
            tar_mean = np.mean(nTargets,axis=0)
            tar_sd = np.std(nTargets,axis=0)
            nTargets -= tar_mean
            nTargets = np.divide(nTargets,tar_sd,out=np.zeros_like(nTargets),where=tar_sd!=0)

        elif(norm == 'divstd'):
            tar_sd = np.std(nTargets,axis=0)
            nTargets = np.divide(nTargets,tar_sd,out=np.zeros_like(nTargets),where=tar_sd!=0)

        return nTargets

    def normalizeTargetsBinaryClass(self):

        '''
        We want to normalize all targets.
        '''

        norm = self.targetNormalization
        nTargets = copy.deepcopy(self.infoDir['hotWin'])

        nTargets[nTargets<5] = 0
        nTargets[nTargets>=5] = 1

        return nTargets.astype(np.uint8)

    def normalizeAlleleFqs(self, fqs):

        '''
        normalize the allele frequencies for the batch
        '''

        norm = self.targetNormalization

        if(norm == 'zscore'):
            allVals = np.concatenate([a.flatten() for a in fqs])
            fqs_mean = np.mean(allVals)
            fqs_sd = np.std(allVals)
            for i in range(len(fqs)):
                fqs[i] = np.subtract(fqs[i],fqs_mean)
                fqs[i] = np.divide(fqs[i],fqs_sd,out=np.zeros_like(fqs[i]),where=fqs_sd!=0)

        elif(norm == 'divstd'):
            allVals = np.concatenate([a.flatten() for a in fqs])
            fqs_sd = np.std(allVals)
            for i in range(len(fqs)):
                fqs[i] = np.divide(fqs[i],fqs_sd,out=np.zeros_like(fqs[i]),where=fqs_sd!=0)

        return fqs

    def on_epoch_end(self):

        if(self.shuffleExamples):
            np.random.shuffle(self.indices)

    def __len__(self):
        return int(np.floor(self.infoDir["numReps"]/self.batch_size))

    @property
    def steps_per_epoch(self):
        return int(np.floor(self.infoDir["numReps"] / self.batch_size))

    def __getitem__(self, idx):

        indices = self.indices[idx*self.batch_size:(idx+1)*self.batch_size]
        X, y = self.__data_generation(indices)
        return X,y

    def to_dataset(self, repeat=True, shuffle=None):
        """Return a tf.data.Dataset for use with model.fit().
        Use TFRecords which pre-padded and pre-normalized, if available.
        If TFRecords is not avaiable, load .npy files and use a two-stage pipeline:

        Stage 1: index → tf.py_function(load + pad single sample)

        Stage 2: [repeat] → shuffle → batch → set_shape → prefetch


        Args:
            repeat: If True (default), the dataset repeats indefinitely so
                    Keras can iterate over it across epochs.
            shuffle: If True or None, shuffle examples, if False, don't shuffle examples

        Returns:
            A tf.data.Dataset that yields (X, y) batches.
        """
        do_shuffle = self.shuffleExamples if shuffle is None else shuffle
        numReps = self.infoDir["numReps"]
        snp_dim = self.maxLen + 2 * self.frameWidth if self.maxLen is not None else None
        tfrecord_path = os.path.join(self.treeDirectory, "data.tfrecord")
        if self.useTFRecord and not os.path.exists(tfrecord.path):
            raise FileNotFoundError(
                    f"TFRecord file not found at {tfrecord_path}. "
                    "Run npy_to_tfrecord.py first, or set useTFRecord=False to use .npy files directly."
                    )
        use_tfrecord = self.useTFRecord and os.path.exists(tfrecord.path)

        if self.seqD:
            # ------------------------------------------------------------------
            # Pool-seq path: stochastic resampling per epoch — skip cache().
            # Keep the original batch-level tf.py_function approach.
            # ------------------------------------------------------------------
            all_indices = np.arange(numReps)
            ds = tf.data.Dataset.from_tensor_slices(all_indices)

            if do_shuffle:
                ds = ds.shuffle(buffer_size=numReps, reshuffle_each_iteration=True)

            ds = ds.batch(self.batch_size)

            def _py_gen_pool(batch_indices):
                batch_indices = batch_indices.numpy().astype(np.int64)
                z, targets = self.__data_generation(batch_indices)
                return z, targets

            def _map_fn_pool(batch_indices):
                z, targets = tf.py_function(
                    func=_py_gen_pool,
                    inp=[batch_indices],
                    Tout=[tf.float32, tf.float32],
                )
                z.set_shape([None, None, None])  # (batch, numSNPs+2*frameWidth, 2)
                targets.set_shape([None, 1])     # (batch, 1)
                return z, targets

            ds = ds.map(_map_fn_pool, num_parallel_calls=tf.data.AUTOTUNE)

            if repeat:
                ds = ds.repeat()

            ds = ds.prefetch(tf.data.AUTOTUNE)
            return ds
        # ------------------------------------------------------------------
        # Standard path: TFRecord if available, else per-sample .npy loading
        # ------------------------------------------------------------------
        # ------------------------------------------------------------------
        # Stage 1: load raw haps, pos, rho — source differs, output is same
        # ------------------------------------------------------------------
        if use_tfrecord:
            def _parse_tfrecord(serialized):
                features = tf.io.parse_single_example(serialized, {
                    'haps':       tf.io.VarLenFeature(tf.float32),
                    'haps_shape': tf.io.VarLenFeature(tf.int64),
                    'pos':        tf.io.VarLenFeature(tf.float32),
                    'rho':        tf.io.VarLenFeature(tf.float32),
                })
                haps_shape = tf.cast(tf.sparse.to_dense(features['haps_shape']), tf.int32)
                haps = tf.reshape(tf.sparse.to_dense(features['haps']), haps_shape)
                pos  = tf.sparse.to_dense(features['pos'])
                rho  = tf.reshape(tf.sparse.to_dense(features['rho']), [1])
                return haps, pos, rho

            ds = tf.data.TFRecordDataset(tfrecord_path)
            ds = ds.map(_parse_tfrecord, num_parallel_calls=tf.data.AUTOTUNE)

        else:
            all_indices = np.arange(numReps)

            def _load_npy(idx):
                idx      = int(idx.numpy())
                haps     = np.load(os.path.join(self.treesDirectory, f"{idx}_haps.npy"))
                pos      = np.load(os.path.join(self.treesDirectory, f"{idx}_pos.npy"))
                rho      = np.array([self.normalizedTargets[idx]], dtype=np.float32)
                return haps.astype(np.float32), pos.astype(np.float32), rho

            def _map_load_npy(idx):
                haps, pos, rho = tf.py_function(
                    func=_load_npy, inp=[idx],
                    Tout=[tf.float32, tf.float32, tf.float32])
                haps.set_shape([None, None])
                pos.set_shape([None])
                rho.set_shape([1])
                return haps, pos, rho

            ds = tf.data.Dataset.from_tensor_slices(all_indices)
            ds = ds.map(_map_load_npy, num_parallel_calls=tf.data.AUTOTUNE)

        # ------------------------------------------------------------------
        # Stage 2: transforms — identical for both paths
        # ------------------------------------------------------------------
        def _transform(haps, pos, rho):
            def _np_transform(haps_np, pos_np):
                haps_np = haps_np.numpy()
                pos_np  = pos_np.numpy()
                if self.realLinePos:
                    pos_np = pos_np / self.infoDir["ChromosomeLength"]
                if self.sortInds:
                    haps_np = np.transpose(self.sort_min_diff(np.transpose(haps_np)))
                if self.maxLen is not None:
                    haps_out, pos_out = self.pad_HapsPos(
                        [haps_np], [pos_np],
                        maxSNPs=self.maxLen,
                        frameWidth=self.frameWidth,
                        center=self.center)
                    haps_np = haps_out[0]
                    pos_np  = pos_out[0]
                    pos_np  = np.where(pos_np  == -1.0, self.posPadVal, pos_np)
                    haps_np = np.where(haps_np <   1.0, self.ancVal,    haps_np)
                    haps_np = np.where(haps_np >   1.0, self.padVal,    haps_np)
                    haps_np = np.where(haps_np ==  1.0, self.derVal,    haps_np)
                return haps_np.astype(np.float32), pos_np.astype(np.float32)

            haps, pos = tf.py_function(
                func=_np_transform, inp=[haps, pos],
                Tout=[tf.float32, tf.float32])
            haps.set_shape([snp_dim, None])
            pos.set_shape([snp_dim])
            rho.set_shape([1])
            return haps, pos, rho

        ds = ds.map(_transform, num_parallel_calls=tf.data.AUTOTUNE)

        # ------------------------------------------------------------------
        # Stage 3: shuffle, repeat, batch, prefetch — shared
        # ------------------------------------------------------------------
        if do_shuffle:
            ds = ds.shuffle(buffer_size=min(numReps, 2000), reshuffle_each_iteration=True)
        if repeat:
            ds = ds.repeat()
        ds = ds.batch(self.batch_size)
        ds = ds.map(lambda h, p, t: ((h, p), t), num_parallel_calls=tf.data.AUTOTUNE)
        ds = ds.prefetch(tf.data.AUTOTUNE)
        return ds


    def __data_generation(self, batchTreeIndices):

        haps = []
        pos = []
        for treeIndex in batchTreeIndices:
            haps.append(np.load(os.path.join(self.treesDirectory,str(treeIndex)+"_haps.npy")))
            pos.append(np.load(os.path.join(self.treesDirectory,str(treeIndex)+"_pos.npy")))
        respectiveNormalizedTargets = [[t] for t in self.normalizedTargets[batchTreeIndices]]
        targets = np.array(respectiveNormalizedTargets)

        if(self.realLinePos):
            for p in range(len(pos)):
                pos[p] = pos[p] / self.infoDir["ChromosomeLength"]

        if(self.sortInds):
            for i in range(len(haps)):
                haps[i] = np.transpose(self.sort_min_diff(np.transpose(haps[i])))

        if self.seqD:
            # simulate pool-sequencing
            if(self.maxLen != None):
                # convert the haps to allele frequecies and then pad
                haps,pos = self.padAlleleFqs(haps,pos,
                    maxSNPs=self.maxLen,
                    frameWidth=self.frameWidth,
                    center=self.center)

                haps=np.where(haps == -1.0, self.posPadVal,haps)
                pos=np.where(pos == -1.0, self.posPadVal,pos)
                z = np.stack((haps,pos), axis=-1)

                return z, targets
        else:
            if(self.maxLen != None):
                # pad
                haps,pos = self.pad_HapsPos(haps,pos,
                    maxSNPs=self.maxLen,
                    frameWidth=self.frameWidth,
                    center=self.center)

                pos=np.where(pos == -1.0, self.posPadVal,pos)
                haps=np.where(haps < 1.0, self.ancVal, haps)
                haps=np.where(haps > 1.0, self.padVal, haps)
                haps=np.where(haps == 1.0, self.derVal, haps)

                return (haps,pos), targets


class VCFBatchGenerator(keras.utils.Sequence):
    """Basically same as SequenceBatchGenerator Class except for VCF files"""
    def __init__(self,
            INFO,
            CHROM,
            winLen,
            numWins,
            IDs,
            GT,
            POS,
            batchSize=64,
            maxLen=None,
            frameWidth=0,
            center=False,
            sortInds=False,
            ancVal = -1,
            padVal = -1,
            derVal = 1,
            realLinePos = True,
            posPadVal = 0,
            phase=None,
            seed=None
            ):

        super().__init__()
        self.INFO=INFO
        self.CHROM=CHROM
        self.winLen=winLen
        self.numWins=numWins
        self.indices=np.arange(self.numWins)
        self.IDs=IDs
        self.GT=GT
        self.POS=POS
        self.batch_size = batchSize
        self.maxLen = maxLen
        self.frameWidth = frameWidth
        self.center = center
        self.sortInds=sortInds
        self.ancVal = ancVal
        self.padVal = padVal
        self.derVal = derVal
        self.realLinePos = realLinePos
        self.posPadVal = posPadVal
        self.phase=phase
        self.seed=seed

        if self.seed:
            os.environ['PYTHONHASHSEED']=str(self.seed)
            random.seed(self.seed)
            np.random.seed(self.seed)


    def pad_HapsPosVCF(self,haplotypes,positions,maxSNPs=None,frameWidth=0,center=False):
        '''
        pads the haplotype and positions tensors
        to be uniform with the largest tensor
        '''

        haps = haplotypes
        pos = positions

        nSNPs=[]

        #Normalize the shape of all haplotype vectors with padding
        for i in range(len(haps)):
            numSNPs = haps[i].shape[0]
            nSNPs.append(numSNPs)
            paddingLen = maxSNPs - numSNPs
            if(center):
                prior = paddingLen // 2
                post = paddingLen - prior
                haps[i] = np.pad(haps[i],((prior,post),(0,0)),"constant",constant_values=2.0)
                pos[i] = np.pad(pos[i],(prior,post),"constant",constant_values=-1.0)

            else:
                haps[i] = np.pad(haps[i],((0,paddingLen),(0,0)),"constant",constant_values=2.0)
                pos[i] = np.pad(pos[i],(0,paddingLen),"constant",constant_values=-1.0)

        haps = np.array(haps,dtype='float32')
        pos = np.array(pos,dtype='float32')

        if(frameWidth):
            fw = frameWidth
            haps = np.pad(haps,((0,0),(fw,fw),(fw,fw)),"constant",constant_values=2.0)
            pos = np.pad(pos,((0,0),(fw,fw)),"constant",constant_values=-1.0)
        return haps,pos,nSNPs


    def __getitem__(self, idx):

        indices = self.indices[idx*self.batch_size:(idx+1)*self.batch_size]
        X, nSNPs = self.__data_generation(indices)

        return X, self.CHROM, self.winLen, self.INFO, nSNPs


    def __data_generation(self, indices):

        if self.seed:
            os.environ['PYTHONHASHSEED']=str(self.seed)
            random.seed(self.seed)
            np.random.seed(self.seed)

        #def __getitem__(self, idx):
        genos=self.GT
        GT=self.GT.to_haplotypes()
        diploid_check=[]
        for n in range(1,len(genos[0]),2):
            GTB=GT[:,n:n+1]
            if np.unique(GTB).shape[0] == 1 and np.unique(GTB)[0] == -1:
                diploid_check.append(0)
            else:
                diploid_check.append(1)
                break
        if 1 in diploid_check:
            GT=np.array(GT)
        else:
            GT=GT[:,::2] #Select only the first of the genotypes
        GT = np.where(GT == -1, 2, GT) # Code missing data as 2, these will ultimately end up being transformed to the pad value

        if not self.phase:
            np.random.shuffle(np.transpose(GT))

        haps,pos=[],[]
        for i in indices:
            haps.append(GT[self.IDs[i][0]:self.IDs[i][1]])
            pos.append(self.POS[self.IDs[i][0]:self.IDs[i][1]])

        if(self.realLinePos):
            for i in range(len(pos)):
                pos[i] = (pos[i]-(self.winLen*indices[i])) / self.winLen

        if(self.sortInds):
            for i in range(len(haps)):
                haps[i] = np.transpose(sort_min_diff(np.transpose(haps[i])))

        if(self.maxLen != None):
            haps,pos,nSNPs = self.pad_HapsPosVCF(haps,pos,
                maxSNPs=self.maxLen,
                frameWidth=self.frameWidth,
                center=self.center)

            pos=np.where(pos == -1.0, self.posPadVal,pos)
            haps=np.where(haps < 1.0, self.ancVal, haps)
            haps=np.where(haps > 1.0, self.padVal, haps)
            haps=np.where(haps == 1.0, self.derVal, haps)

            return (haps,pos), nSNPs


class POOLBatchGenerator(keras.utils.Sequence):
    """Basically same as SequenceBatchGenerator Class except for POOL files"""
    def __init__(self,
            INFO,
            CHROM,
            winLen,
            numWins,
            IDs,
            GT,
            POS,
            batchSize=64,
            maxLen=None,
            frameWidth=0,
            center=False,
            sortInds=False,
            ancVal = -1,
            padVal = -1,
            derVal = 1,
            realLinePos = True,
            posPadVal = 0,
            normType = 'zscore',
            seed = None
            ):

        super().__init__()
        self.INFO=INFO
        self.normType = normType
        self.CHROM=CHROM
        self.winLen=winLen
        self.numWins=numWins
        self.indices=np.arange(self.numWins)
        self.IDs=IDs
        self.GT=GT
        self.POS=POS
        self.batch_size = batchSize
        self.maxLen = maxLen
        self.frameWidth = frameWidth
        self.center = center
        self.sortInds=sortInds
        self.ancVal = ancVal
        self.padVal = padVal
        self.derVal = derVal
        self.realLinePos = realLinePos
        self.posPadVal = posPadVal
        self.seed = seed

        if self.seed:
            os.environ['PYTHONHASHSEED']=str(self.seed)
            random.seed(self.seed)
            np.random.seed(self.seed)

    def padFqs(self,haplotypes,positions,maxSNPs=None,frameWidth=0,center=False):
        '''
        normalize, and pad the haplotype and positions tensors
        to be uniform with the largest tensor
        '''

        fqs = haplotypes
        pos = positions

        # Normalize
        fqs = self.normalizeAlleleFqs(fqs)

        nSNPs=[]
        # Pad
        for i in range(len(fqs)):
            numSNPs = fqs[i].shape[0]
            nSNPs.append(numSNPs)
            paddingLen = maxSNPs - numSNPs
            if(center):
                prior = paddingLen // 2
                post = paddingLen - prior
                fqs[i] = np.pad(fqs[i],(prior,post),"constant",constant_values=-1.0)
                pos[i] = np.pad(pos[i],(prior,post),"constant",constant_values=-1.0)

            else:
                if(paddingLen < 0):
                    fqs[i] = np.pad(fqs[i],(0,0),"constant",constant_values=-1.0)[:paddingLen]
                    pos[i] = np.pad(pos[i],(0,0),"constant",constant_values=-1.0)[:paddingLen]
                else:
                    fqs[i] = np.pad(fqs[i],(0,paddingLen),"constant",constant_values=-1.0)
                    pos[i] = np.pad(pos[i],(0,paddingLen),"constant",constant_values=-1.0)

        fqs = np.array(fqs,dtype='float32')
        pos = np.array(pos,dtype='float32')

        if(frameWidth):
            fw = frameWidth
            fqs = np.pad(fqs,((0,0),(fw,fw)),"constant",constant_values=-1.0)
            pos = np.pad(pos,((0,0),(fw,fw)),"constant",constant_values=-1.0)

        return fqs,pos,nSNPs


    def normalizeAlleleFqs(self, fqs):

        '''
        normalize the allele frequencies for the batch
        '''

        norm = self.normType

        if(norm == 'zscore'):
            allVals = np.concatenate([a.flatten() for a in fqs])
            fqs_mean = np.mean(allVals)
            fqs_sd = np.std(allVals)
            for i in range(len(fqs)):
                fqs[i] = np.subtract(fqs[i],fqs_mean)
                fqs[i] = np.divide(fqs[i],fqs_sd,out=np.zeros_like(fqs[i]),where=fqs_sd!=0)

        elif(norm == 'divstd'):
            allVals = np.concatenate([a.flatten() for a in fqs])
            fqs_sd = np.std(allVals)
            for i in range(len(fqs)):
                fqs[i] = np.divide(fqs[i],fqs_sd,out=np.zeros_like(fqs[i]),where=fqs_sd!=0)

        return fqs


    def __getitem__(self, idx):

        indices = self.indices[idx*self.batch_size:(idx+1)*self.batch_size]
        X, nSNPs = self.__data_generation(indices)

        return X, self.CHROM, self.winLen, self.INFO, nSNPs


    def __data_generation(self, indices):

        if self.seed:
            os.environ['PYTHONHASHSEED']=str(self.seed)
            random.seed(self.seed)
            np.random.seed(self.seed)

        GT=self.GT

        haps,pos=[],[]
        for i in indices:
            haps.append(GT[self.IDs[i][0]:self.IDs[i][1]])
            pos.append(self.POS[self.IDs[i][0]:self.IDs[i][1]])

        if(self.realLinePos):
            for i in range(len(pos)):
                pos[i] = (pos[i]-(self.winLen*indices[i])) / self.winLen

        if(self.sortInds):
            for i in range(len(haps)):
                haps[i] = np.transpose(sort_min_diff(np.transpose(haps[i])))

        # pad the allele freqs and positions
        if(self.maxLen != None):
            haps,pos,nSNPs = self.padFqs(haps,pos,
                maxSNPs=self.maxLen,
                frameWidth=self.frameWidth,
                center=self.center)

            haps=np.where(haps == -1.0, self.posPadVal,haps)
            pos=np.where(pos == -1.0, self.posPadVal,pos)
            np.set_printoptions(threshold=sys.maxsize)
            z = np.stack((haps,pos), axis=-1)

            return z, nSNPs


